name: Deploy Cloudflare Connector to Azure ACI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az container create \
              --resource-group ${{ vars.RESOURCE_GROUP }} \
              --name cloudflared-connector-container \
              --image cloudflare/cloudflared:latest \
              --os-type Linux \
              --memory 1 \
              --cpu 1 \
              --restart-policy Always \
              --secure-environment-variables TUNNEL_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }} \
              --command-line "cloudflared tunnel --no-autoupdate run --token $TUNNEL_TOKEN"
